---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	ingest(ingest)
	split_or_buffer(split_or_buffer)
	summarize(summarize)
	enrich_pending_events(enrich_pending_events)
	build_context(build_context)
	persist(persist)
	__end__([<p>__end__</p>]):::last
	__start__ --> ingest;
	build_context --> persist;
	enrich_pending_events --> persist;
	ingest --> split_or_buffer;
	split_or_buffer -.-> __end__;
	split_or_buffer -.-> summarize;
	summarize --> build_context;
	summarize --> enrich_pending_events;
	persist --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
